CREATE DATABASE dbSistema2;

use dbSistema2;

CREATE TABLE tbCliente(
	CLI_CODIGO int not null auto_increment,
	CLI_NOME varchar(50) not null, 
	CLI_CPF varchar(15) not null unique,
	CLI_RUA varchar(50) not null,
	CLI_NUMERO int null,
	CLI_BAIRRO varchar(50) not null,
	primary key(CLI_CODIGO)
);

CREATE TABLE tbVendedor(
	VEN_CODIGO int not null auto_increment,
    VEN_NOME varchar(50) not null,
    VEN_CPF varchar(15) not null unique,
    primary key(VEN_CODIGO)
);

CREATE TABLE tbFornecedor(
	FOR_CODIGO int not null auto_increment,
    FOR_RAZAO_SOC varchar(50) not null,
    FOR_CNPJ varchar(20) not null unique,
    FOR_ESPECIALIDADE varchar(50) not null,
    primary key(FOR_CODIGO)
);

CREATE TABLE tbProduto(
	PRO_CODIGO int not null auto_increment,
	PRO_NOME varchar(50) not null,
	PRO_QTDE int not null,
	PRO_UNIDADE varchar(10),
	PRO_PRECO_UNIT double(10,2),
	FOR_CODIGO int not null,
    primary key(PRO_CODIGO),
    constraint fk_tbFornecedor_tbProduto foreign key(FOR_CODIGO) references tbFornecedor(FOR_CODIGO)
);

CREATE TABLE tbPedido(
	PED_CODIGO int not null auto_increment,
	PED_DATA date,
	CLI_CODIGO int,
	VEN_CODIGO int,
    primary key (PED_CODIGO),
    constraint fk_tbPedido_tbCliente foreign key (CLI_CODIGO) references tbCliente(CLI_CODIGO),
    constraint fk_tbPedido_tbVendedor foreign key (VEN_CODIGO) references tbVendedor(VEN_CODIGO)
);

CREATE TABLE tbPedidoProduto(
	PEP_CODIGO int not null auto_increment,
	PED_CODIGO int not null,
	PRO_CODIGO int not null,
	PEP_QTDE int not null,
    primary key (PEP_CODIGO),
    constraint fk_tbPedidoProduto_tbPedido foreign key (PED_CODIGO) references tbPedido(PED_CODIGO),
    constraint fk_tbPedidoProduto_tbProduto foreign key (PRO_CODIGO) references tbProduto(PRO_CODIGO)
);

-- Cadastro de Clientes --
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Sofia Rodriguez','781630492356','Rua do Sol',123,'Centro');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Lucas Santos','213540289654','Avenida das Flores',456,' Jardim Botânico');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Isabella Silva','846529018364','Rua dos Pinheiros',789,' Pinheiros');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Miguel Almeida','970218634125','Avenida da Praia',234,' Copacabana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Ana Paula Costa','384769521039','Rua das Palmeiras',567,' Jardim Europa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Tiago Ferreira','872109346523','Avenida das Dunas',890,' Barra da Tijuca');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Júlia Vieira','457982130964','Rua dos Cravos',123,' Vila Madalena');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Pedro Carvalho','925468713024','Avenida das Gaivotas',456,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Lara Castro','345671982156','Rua das Acácias',789,' Perdizes');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Guilherme Souza','657890243561','Avenida das Amendoeiras',234,' Lagoa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Giovanna Oliveira','231490785634','Rua dos Girassóis',567,' Itaim Bibi');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Rafael Pereira','876512093467','Avenida das Mangueiras',890,' Jardim Botânico');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Laura Martins','456389120367','Rua dos Crisântemos',123,' Jardins');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Gabriel Lima','981726304567','Avenida das Palmeiras',456,' Leblon');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Beatriz Gonçalves','456870913284','Rua das Orquídeas',789,' Vila Nova Conceição');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Matheus Fernandes','736482019576','Avenida das Andorinhas',234,' Gávea');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Manuela Barbosa','921067354890','Rua dos Lírios',567,' Morumbi');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('João Batista','345890172463','Avenida das Violetas',890,' Laranjeiras');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Maria Eduarda Santos','821947365019','Rua das Tulipas',123,' Brooklin');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('André Costa','673218956740','Avenida das Gaivotas',456,' Flamengo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Carolina Oliveira','120934875621','Rua dos Cravos',789,' Higienópolis');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Carlos Eduardo Rodrigues','548903216734','Avenida das Mangueiras',234,' Botafogo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Marcela Gomes','984761325019','Rua das Rosas',567,' Jardim América');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Felipe Pereira','278931456023','Avenida das Flores',890,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Bruna Alves','679183245067','Rua das MaCPFaridas',123,' Vila Mariana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Bruno Sousa','567890213456','Avenida das Amendoeiras',456,' Copacabana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Fernanda Ferreira','231456789012','Rua dos Jacintos',789,' Vila Olímpia');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Vinicius Santos','781902356014','Avenida das Andorinhas',234,' Leblon');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Letícia Silva','908731256042','Rua das Azaléias',567,' Santana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Leonardo Rodrigues','390574816239','Avenida das Violetas',890,' São Conrado');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Camila Souza','246879315021','Rua dos Jasmim',123,' Pinheiros');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Victor Martins','109834562746','Avenida das Palmeiras',456,' Humaitá');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Mariana Lima','927456381024','Rua das MaCPFaridas',789,' Tatuapé');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Gustavo Castro','874910265310','Avenida das Gaivotas',234,' Laranjeiras');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Luiza Almeida','345682719034','Rua dos Jasmins',567,' Vila Mariana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Paulo Pereira','698523140765','Avenida das Acácias',890,' Lagoa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Bárbara Oliveira','216478903512','Rua das Orquídeas',123,' Morumbi');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Ricardo Silva','769012384560','Avenida das Violetas',456,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Daniela Costa','893140256708','Rua dos Cravos',789,' Jardim Paulista');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Eduardo Santos','431297560862','Avenida das Mangueiras',234,' Flamengo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Isadora Vieira','216780345689','Rua das Rosas',567,' Vila Nova Conceição');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Renan Castro','108736429571','Avenida das Andorinhas',890,' Gávea');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Natália Fernandes','290876415239','Rua dos Lírios',123,' Jardim Europa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Henrique Sousa','345698172634','Avenida das Amendoeiras',456,' Laranjeiras');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Luana Gomes','623485791036','Rua das Tulipas',789,' Itaim Bibi');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Lucas Ferreira','984712536009','Avenida das Gaivotas',234,' Copacabana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Gabriela Batista','431257890216','Rua dos Girassóis',567,' Jardins');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Rodrigo Barbosa','312546709832','Avenida das Palmeiras',890,' Leblon');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Ana Luiza Santos','178640925367','Rua das Acácias',123,' Perdizes');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Arthur Costa','521098367459','Avenida das Amendoeiras',456,' Botafogo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Amanda Pereira','932087645019','Rua dos Crisântemos',789,' Vila Madalena');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Lucas Carvalho','465890321745','Avenida das Mangueiras',234,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Letícia Souza','218703956042','Rua das Orquídeas',567,' Morumbi');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Daniel Martins','847631902560','Avenida das Violetas',890,' Barra da Tijuca');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Mariana Oliveira','340987621543','Rua dos Pinheiros',123,' Pinheiros');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Samuel Rodrigues','962175348021','Avenida da Praia',456,' Copacabana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Thaís Alves','490871235678','Rua das Palmeiras',789,' Jardim Botânico');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Gabriel Vieira','784509162346','Avenida das Dunas',234,' Leblon');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Marina Ferreira','120385674905','Rua dos Cravos',567,' Vila Mariana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Marcos Santos','756049812630','Avenida das Gaivotas',890,' Lagoa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Luana Pereira','456329871240','Rua dos Jasmins',123,' Jardim Paulista');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Cauã Silva','872013496513','Avenida das Acácias',456,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Beatriz Oliveira','931246578019','Rua das Orquídeas',789,' Jardins');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Breno Castro','450231768914','Avenida das Violetas',234,' Botafogo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Bruna Souza','678123904651','Rua dos Crisântemos',567,' Laranjeiras');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Rafaela Gomes','924156738021','Avenida das Mangueiras',890,' Flamengo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('João Pedro Almeida','783412905164','Rua das Rosas',123,' Vila Nova Conceição');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Valentina Costa','465219378021','Rua dos Lírios',789,' Morumbi');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Davi Sousa','102367890543','Avenida das Amendoeiras',234,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Laura Fernandes','309854176230','Rua das Tulipas',567,' Jardim Europa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Gustavo Lima','675489032146','Avenida das Gaivotas',890,' Copacabana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Vitória Martins','238976541021','Rua dos Girassóis',123,' Vila Madalena');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Rafael Oliveira','864320159342','Avenida das Palmeiras',456,' Leblon');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Ana Clara Santos','231459086730','Rua das Acácias',789,' Pinheiros');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Pedro Henrique Costa','780961245312','Avenida das Amendoeiras',234,' Barra da Tijuca');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Fernanda Rodrigues','431256897013','Rua dos Crisântemos',567,' Vila Mariana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Eduardo Silva','982345617093','Avenida das Mangueiras',890,' Lagoa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Mariana Souza','671430298567','Rua dos Jasmins',123,' Jardim Paulista');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Gabriel Ferreira','125678903421','Avenida das Acácias',456,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Júlia Gomes','781054329076','Rua das Orquídeas',789,' Jardins');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Thiago Pereira','430198762145','Avenida das Violetas',234,' Botafogo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Maria Clara Alves','231547890167','Rua dos Cravos',567,' Laranjeiras');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Lucas Rodrigues','945123678019','Avenida das Mangueiras',890,' Flamengo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Bianca Oliveira','578901234560','Rua das Rosas',123,' Vila Nova Conceição');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Bruno Castro','467823190548','Avenida das Andorinhas',456,' Gávea');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Giovana Sousa','120498756341','Rua dos Lírios',789,' Morumbi');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Felipe Gomes','954120378607','Avenida das Amendoeiras',234,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Maria Luiza Ferreira','687231054912','Rua das Tulipas',567,' Jardim Europa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Lucas Lima','239071865041','Avenida das Gaivotas',890,' Copacabana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Isabela Martins','891345207631','Rua dos Girassóis',123,' Vila Madalena');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Pedro Castro','891345329076','Avenida das Palmeiras',456,' Leblon');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Larissa Souza','207631762145','Rua das Acácias',789,' Pinheiros');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Vinícius Costa','762145890167','Avenida das Amendoeiras',234,' Barra da Tijuca');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Natália Rodrigues','890167678019','Rua dos Crisântemos',567,' Vila Mariana');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Rafaela Alves','678019234560','Avenida das Mangueiras',890,' Lagoa');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('João Vitor Oliveira','234560190548','Rua dos Jasmins',123,' Jardim Paulista');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Luana Castro','190548756341','Avenida das Acácias',456,' Ipanema');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Gabriel Sousa','756341378607','Rua das Orquídeas',789,' Jardins');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Carolina Ferreira','378607054912','Avenida das Violetas',234,' Botafogo');
insert into tbCliente (CLI_NOME, CLI_CPF, CLI_RUA, CLI_NUMERO, CLI_BAIRRO) value ('Renato Silva','54912865041','Rua dos Cravos',567,' Laranjeiras');


-- Tabela de Vendedores --
insert into tbVendedor (VEN_NOME, VEN_CPF) value ('Gabriel Heleno', '12332156769');
insert into tbVendedor (VEN_NOME, VEN_CPF) value ('Luis Gustavo', '98765498769');
insert into tbVendedor (VEN_NOME, VEN_CPF) value ('Michael Jesson', '99912355612');
insert into tbVendedor (VEN_NOME, VEN_CPF) value ('Fred da Silva', '87999385321');
insert into tbVendedor (VEN_NOME, VEN_CPF) value ('Alsione Arruda', '34112543399');

-- Tabela de Fornecedor --
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Suprimentos Globais', '23.456.789/0002-01', 'Alimentos');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Distribuição Versátil', '34.567.890/0003-02', 'Casa e Banho');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Artigos Essenciais', '45.678.901/0004-03', 'Eletrônicos');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Produtos Multifuncionais', '56.789.012/0005-04', 'Ferramentas');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Fornecedores de Tudo', '67.890.123/0006-05', 'Higiene');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Soluções Abrangentes', '78.901.234/0007-06', 'Iluminação');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Abastecimento Universal', '89.012.345/0008-07', 'Informática');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Importação e Exportação Diversificada', '90.123.456/0009-08', 'Limpeza');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Parcerias de Variedades', '01.234.567/0010-09', 'Papelaria');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Logística de Produtos Variados', '12.345.678/0011-10', 'Temperos');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Mercadorias Abastecidas', '23.456.789/0012-11', 'Utensílios de Cozinha');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Fontes de Produtos Multimarcas', '34.567.890/0013-12', 'Utilidades Domésticas');
insert into tbFornecedor (FOR_RAZAO_SOC, FOR_CNPJ, FOR_ESPECIALIDADE) value ('Ampliações de Estoques', '45.678.901/0014-13', 'Vestuário');

-- Tabela de Produto --
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Açúcar',1, 'kg', 2.49,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Arroz',5, 'kg', 22.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Biscoito',200, 'g', 3.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Cápsulas de Café',10, 'unidade', 7.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Chocolate',100, 'g', 3.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Iogurte',500, 'g', 2.49,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Leite',1, 'L', 3.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Manga',1, 'unidade', 2.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Manteiga',200, 'g', 5.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Molho de Tomate',350, 'g', 1.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Óleo de Cozinha',900, 'mL', 4.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Queijo Mussarela',250, 'g', 7.99,1);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Chuveiro',1, 'unidade', 29.99,2);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Bateria 9V',1, 'unidade', 12.99,3);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Bateria AA',4, 'unidade', 7.99,3);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Fone de Ouvido',1, 'unidade', 39.99,3);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Chave de Fenda',1, 'unidade', 6.99,4);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Lanterna',1, 'unidade', 19.99,4);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Martelo',1, 'unidade', 14.99,4);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Algodão',50, 'g', 1.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Álcool Gel',500, 'mL', 9.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Cotonetes',75, 'unidade', 2.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Escova de Cabelo',1, 'unidade', 5.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Luvas Descartáveis',50, 'unidade', 14.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Máquina de Cortar Cabelo',1, 'unidade', 49.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Papel Higiênico',12, 'rolos', 14.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Pasta de Dente',90, 'g', 3.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Protetor Solar',120, 'mL', 29.99,5);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Lâmpada LED',1, 'unidade', 12.99,6);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Cartucho de Tinta',1, 'unidade', 22.99,7);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Disco Rígido Externo',1, 'unidade', 329.99,7);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Mouse Sem Fio',1, 'unidade', 29.99,7);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Amaciante de roupas',2, 'L', 11.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Balde para Lixo',1, 'unidade', 8.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Bobina de Papel Toalha',2, 'unidade', 6.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Bom Ar',360, 'mL', 8.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Detergente',1, 'L', 4.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Esponja de Aço',1, 'unidade', 2.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Limpador Multiuso',1, 'L', 7.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Pano de Chão',1, 'unidade', 3.99,8);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Adesivo Instantâneo',1, 'unidade', 7.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Bloco de Anotações',1, 'unidade', 4.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Caderno',1, 'unidade', 12.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Cartela de Canetas',12, 'unidade', 6.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Estilete',1, 'unidade', 3.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Fita Adesiva',1, 'unidade', 2.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Lápis de Cor',12, 'unidade', 8.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Pincel para Pintura',1, 'unidade', 5.99,9);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Alho',500, 'g', 5.99,10);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Faca de Cozinha',1, 'unidade', 19.99,11);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Garfo de Mesa',1, 'unidade', 1.99,11);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Jogo de Copos',6, 'unidade', 24.99,11);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Jogo de Facas',5, 'unidade', 59.99,11);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Balde para Pipoca',1, 'unidade', 3.99,12);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Pote de Plástico',1, 'unidade', 2.99,12);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Capa de Chuva',1, 'unidade', 9.99,13);
insert into tbProduto (PRO_NOME, PRO_QTDE, PRO_UNIDADE, PRO_PRECO_UNIT, FOR_CODIGO) value ('Guarda-chuva',1, 'unidade', 12.99,13);

-- Tabela Pedido --
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-02', 67, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-03', 29, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-04', 92, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-05', 13, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-06', 41, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-07', 55, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-08', 77, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-09', 22, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-10', 38, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-11', 89, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-12', 17, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-13', 43, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-14', 6, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-15', 83, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-16', 9, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-17', 99, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-18', 51, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-19', 70, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-20', 25, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-21', 8, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-22', 47, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-23', 61, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-24', 34, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-25', 98, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-26', 72, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-27', 15, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-28', 78, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-29', 50, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-30', 26, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2019-10-31', 85, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-02', 45, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-03', 20, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-04', 39, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-05', 31, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-06', 56, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-07', 69, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-08', 11, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-09', 90, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-10', 76, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-11', 24, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-12', 95, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-13', 57, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-14', 28, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-15', 65, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-16', 97, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-17', 46, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-18', 63, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-19', 80, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-20', 14, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-21', 32, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-22', 62, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-23', 40, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-24', 96, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-25', 2, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-26', 53, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-27', 35, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-28', 87, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-29', 71, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-30', 1, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2020-10-31', 30, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-02', 81, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-03', 12, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-04', 68, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-05', 16, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-06', 48, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-07', 64, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-08', 58, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-09', 19, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-10', 54, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-11', 21, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-12', 4, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-13', 49, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-14', 42, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-15', 60, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-16', 75, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-17', 86, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-18', 7, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-19', 36, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-20', 91, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-21', 84, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-22', 73, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-23', 44, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-24', 27, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-25', 66, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-26', 10, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-27', 79, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-28', 18, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-29', 52, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-30', 5, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2021-10-31', 93, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-02', 23, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-03', 37, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-04', 3, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-05', 88, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-06', 94, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-07', 82, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-08', 59, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-09', 76, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-10', 87, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-11', 71, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-12', 1, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-13', 30, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-14', 81, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-15', 12, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2022-10-16', 68, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-01', 16, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-02', 48, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-03', 64, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-04', 58, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-05', 19, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-06', 54, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-07', 21, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-08', 4, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-09', 49, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-10', 42, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-11', 60, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-12', 75, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-13', 86, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-14', 20, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-15', 39, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-16', 31, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-17', 56, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-18', 69, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-19', 11, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-20', 90, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-21', 76, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-22', 24, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-23', 95, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-24', 57, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-25', 28, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-26', 65, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-27', 97, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-28', 46, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-29', 63, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-30', 80, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-05-31', 14, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-01', 32, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-02', 55, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-03', 77, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-04', 22, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-05', 38, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-06', 89, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-07', 17, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-08', 43, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-09', 6, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-10', 83, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-11', 9, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-12', 99, 4);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-13', 51, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-14', 70, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-15', 25, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-16', 8, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-17', 47, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-18', 61, 3);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-19', 34, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-20', 98, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-21', 72, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-22', 15, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-23', 78, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-24', 50, 2);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-25', 26, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-26', 85, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-27', 45, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-28', 20, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-29', 39, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-06-30', 31, 1);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-07-01', 56, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-07-02', 69, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-07-03', 11, 5);
insert into tbPedido (PED_DATA, CLI_CODIGO, VEN_CODIGO) value ('2023-07-04', 90, 5);

-- Tabela de tbPedidoProduto --
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (85, 49, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (134, 17, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (40, 55, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (82, 8, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (118, 13, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (157, 46, 8);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (137, 48, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (82, 45, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (136, 14, 1);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (72, 16, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (160, 43, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (72, 8, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (127, 26, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 10, 8);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (51, 28, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (98, 50, 1);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (36, 18, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (141, 40, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (143, 21, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (23, 24, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (86, 56, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (23, 27, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (32, 55, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (167, 37, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (35, 11, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (118, 26, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (148, 41, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (58, 4, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (73, 52, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (71, 54, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (61, 28, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (135, 13, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (158, 51, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (120, 18, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (148, 17, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (155, 48, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (116, 21, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (82, 25, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (140, 46, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (59, 2, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (153, 45, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (160, 47, 6);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (166, 52, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (113, 48, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (123, 8, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (51, 56, 8);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (159, 32, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (84, 9, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (120, 24, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (84, 13, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (113, 38, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (123, 2, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (119, 18, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (26, 19, 8);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (16, 47, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (67, 43, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (38, 53, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (165, 4, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (130, 19, 3);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (116, 3, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (104, 4, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (2, 47, 8);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (117, 30, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (31, 9, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (52, 31, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (95, 12, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (162, 27, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (157, 3, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (70, 1, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 43, 8);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (32, 1, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (37, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (31, 36, 2);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (2, 16, 10);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (138, 15, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (119, 53, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (39, 44, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (104, 12, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (88, 18, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (162, 9, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (69, 29, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (133, 36, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (168, 1, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (17, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (55, 20, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (66, 38, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (64, 27, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (64, 6, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (92, 1, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (37, 24, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (61, 22, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (70, 52, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (47, 56, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (53, 15, 8);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (83, 29, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (161, 16, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (16, 51, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (152, 25, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (20, 17, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (165, 56, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (157, 47, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (38, 54, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (126, 50, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (145, 33, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (77, 21, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (107, 55, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (156, 35, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (18, 45, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (7, 22, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (22, 55, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (77, 41, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (20, 47, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (76, 39, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (153, 31, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (54, 43, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (63, 3, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (74, 53, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (137, 24, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (22, 45, 9);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (156, 15, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (94, 56, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (160, 28, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (153, 20, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (37, 37, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (72, 13, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (25, 5, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (137, 5, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (33, 38, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (25, 51, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (167, 30, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (148, 28, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (63, 13, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (63, 33, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (83, 10, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (124, 56, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (105, 36, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (85, 39, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (97, 4, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (27, 21, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (126, 3, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (88, 4, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (102, 54, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (57, 54, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (45, 9, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (150, 19, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (144, 55, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (143, 36, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (117, 22, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (109, 15, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (77, 38, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (79, 23, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (126, 32, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (39, 16, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (30, 30, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (141, 23, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (153, 43, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (66, 23, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (33, 16, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (162, 2, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (77, 28, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (104, 29, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (32, 41, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (22, 45, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (112, 1, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (131, 44, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (163, 32, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (64, 38, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (54, 26, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (110, 54, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (55, 33, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (165, 43, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (156, 30, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (108, 55, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (56, 24, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (94, 39, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (130, 45, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 38, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (104, 1, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (7, 38, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (113, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (108, 21, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (146, 39, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (153, 55, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (81, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (125, 20, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (38, 27, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 23, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (63, 10, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (81, 10, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (53, 39, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (17, 23, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (85, 22, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (26, 11, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (116, 21, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (95, 41, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (130, 19, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (151, 53, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (27, 9, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (23, 21, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (139, 33, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (114, 52, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (24, 28, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (86, 31, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (33, 14, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (140, 54, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (28, 24, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (29, 17, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (96, 27, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (78, 36, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (94, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (120, 31, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (127, 56, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (140, 9, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (86, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (32, 16, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (139, 27, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (139, 23, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (114, 51, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (85, 23, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (91, 39, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (69, 44, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (70, 7, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (115, 43, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (120, 21, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (166, 31, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (165, 53, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (96, 37, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (143, 2, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (166, 4, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (84, 56, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (58, 36, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (131, 50, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (94, 41, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (155, 47, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (70, 12, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (114, 48, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (5, 11, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (151, 48, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (58, 55, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (69, 28, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (29, 53, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (98, 48, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (112, 13, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (7, 54, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (120, 9, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (47, 30, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (30, 11, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (78, 31, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (134, 45, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (125, 50, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (85, 44, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 44, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (153, 18, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (114, 49, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (112, 12, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (130, 16, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (89, 1, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (128, 56, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (147, 55, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (23, 54, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (53, 45, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (120, 38, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (27, 14, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (50, 37, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (82, 43, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (48, 21, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (113, 6, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (113, 3, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (82, 3, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (48, 32, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (153, 17, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (76, 43, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (95, 44, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (36, 45, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (118, 6, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (90, 28, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (54, 6, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (73, 31, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (164, 6, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 47, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (157, 6, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (41, 11, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (22, 30, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (120, 38, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (123, 1, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (159, 47, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (31, 55, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (114, 33, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (114, 47, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (167, 43, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (76, 10, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (50, 10, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (114, 8, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (128, 37, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (85, 55, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (131, 5, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (28, 5, 7);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (62, 5, 5);
insert into tbPedidoProduto (PED_CODIGO, PRO_CODIGO, PEP_QTDE) value (82, 45, 5);
