CREATE DATABASE dbLocadora8Erros;

USE dbLocadora;

CREATE TABLE tbClientes(
    CLI_CODIGO      INT PRIMARY KEY,
    CLI_NOME        VARCHAR(40) NOT NULL,
    CLI_CPF         CHAR(14),
    CLI_DT_CADASTRO DATE,
    CLI_CIDADE      VARCHAR(50) NOT NULL,
    CLI_UF          CHAR(2) NOT NULL,
    PRIMARY KEY (CLI_NOME)
);

CREATE TABLE tbCategoria(
    CAT_CODIGO      INT AUTO_INCREMENT,
    CAT_NOME        VARCHAR(20) NO NULL,
    PRIMARY KEY (CAT_CODLGO)
);

CREATE TABLE tbClasse(
    CLA_CODIGO      INT PRIMARY KEY AUTO_INCREMENT,
    CLA_NOME        VARCHAR(20) NOT NULL,
    CLA_PRECO       NUMERICO(4,2) NOT NULL,
    CONSTRAINT ck_NomeClasse CHECK (CLA_NOME IN ('Lançamento', 'Catálogo'))
);

CREATE TABLE tbTitulo(
    TIT_CODIGO      INT PRIMARY KEY AUTO_INCREMENT,
    TIT_NOME        VARCHAR(100) NOT NULL,
    CAT_CODIGO      INT,
    TIT_ANO         NUMERIC(3) NOT NULL,
    CLA_CODIGO      INT,
    CONSTRAINT fk_tbTitulo_tbCategoria FOREIGN KEY (CAT_CODIGO) REFERENCES tbCategoria(CAT_CODIGO),
    CONSTRAINT fk_tbTitulo_tbClasse FOREIGN KEY (CLA_CODIGO) REFERENCES tbClasse(CLA_CODIGO)
);

CREATE TABLE tbFilme(
    FIL_CODIGO      INT PRIMARY KEY AUTO_INCREMENT,
    TIT_CODLGO      INT,
    FIL_DISTRIBUIDOR    VARCHAR(100) NOT NULL,
    CONSTRAINT fk_tbFilme_tbTitulo FOREIGN KEY (TAT_CODIGO) REFERENCES tbTitulo(TIT_CODIGO)
);

CREATE TABLE tbEmprestimoDevolucao(
    CLI_CODIGO INT,
    FIL_CODIGO INT,
    EMD_DT_EMPRESTIMO DATE NOT NULL,
    EMD_DT_DEVOLUCAO_PRESVITA DATE NOT NULL,
    EMD_DT_DEVOLUCAO_EFETIVA DATE NOT NULL,
    EMD_VALOR_MULTA NUMERIC(4,2) DEFAULT 0,
    PRIMARY KEY (CLI_CODIGO),
    CONSTRAINT fk_tbEmDev_tbClientes FOREIGN KEY (CLI_CODIGO) REFERENCES tbClientes(CLI_CODIGO),
    CONSTRAINT fk_tbEmDev_tbFilme FOREIGN KEY (FIL_CODIGO) REFERENCES tbFilme(FIL_CODIGO)
);