
-- Cadastro de Cliente

INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE ('12345678901', 'João Silva', '2024-02-25', 'Fortaleza', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('98765432100', 'Maria Santos', '2024-02-20', 'Sobral', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('45612378902', 'Carlos Pereira', '2024-01-15', 'Juazeiro do Norte', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('32165498703', 'Ana Souza', '2023-12-10', 'Quixadá', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('74185296304', 'Paulo Lima', '2023-11-05', 'Crato', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('85296374105', 'Fernanda Costa', '2023-10-30', 'Iguatu', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('36925814706', 'Ricardo Almeida', '2023-09-25', 'Russas', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('15935748607', 'Juliana Rocha', '2023-08-15', 'Limoeiro do Norte', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('75395185208', 'Gabriel Mendes', '2023-07-10', 'Canindé', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('25874136909', 'Beatriz Ferreira', '2023-06-05', 'Maracanaú', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('14785236910', 'Lucas Oliveira', '2023-05-20', 'Caucaia', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('36974125811', 'Camila Martins', '2023-04-15', 'Fortaleza', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('25896314712', 'Fernando Nunes', '2023-03-10', 'Juazeiro do Norte', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('14725836913', 'Patrícia Castro', '2023-02-05', 'Sobral', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('36914725814', 'Rafael Silva', '2023-01-30', 'Crato', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('85214796315', 'Amanda Melo', '2022-12-25', 'Iguatu', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('95135748616', 'Thiago Lima', '2022-11-20', 'Russas', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('15975348617', 'Tatiane Ferreira', '2022-10-15', 'Maracanaú', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('35795185218', 'Leonardo Souza', '2022-09-10', 'Quixadá', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('78945612319', 'Juliane Araújo', '2022-08-05', 'Canindé', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('25815975320', 'Roberto Almeida', '2022-07-25', 'Limoeiro do Norte', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('74136925821', 'Vanessa Costa', '2022-06-20', 'Caucaia', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('95125814722', 'Bruno Mendes', '2022-05-15', 'Fortaleza', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('75395185223', 'Tatiana Rocha', '2022-04-10', 'Juazeiro do Norte', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('85236974124', 'Gustavo Oliveira', '2022-03-05', 'Crato', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('75315945625', 'Ana Paula Nunes', '2022-02-25', 'Sobral', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('85296314726', 'Carlos Eduardo', '2022-01-20', 'Iguatu', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('35715985227', 'Fernanda Martins', '2021-12-15', 'Russas', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('14725836928', 'Rafael Silva', '2021-11-10', 'Maracanaú', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('36985214729', 'Patrícia Castro', '2021-10-05', 'Quixadá', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('15975348630', 'Leonardo Souza', '2021-09-25', 'Canindé', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('75395185231', 'Juliane Araújo', '2021-08-20', 'Limoeiro do Norte', 'CE'),
INSERT INTO tbCliente (CLI_CPF, CLI_NOME, CLI_DATA_CADASTRO, CLI_CIDADE, CLI_UF) VALUE('25874136932', 'Roberto Almeida', '2021-07-15', 'Caucaia', 'CE');

-- Cadastro de Categoria

INSERT INTO tbCategoria (CAT_NOME) VALUE ('Ação'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Comédia'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Drama'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Ficção Científica'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Terror'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Suspense'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Romance'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Fantasia'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Animação'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Documentário'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Musical'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Guerra'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Aventura'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Policial'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Faroeste'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Histórico'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Esportes'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Infantil'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Biografia'),
INSERT INTO tbCategoria (CAT_NOME) VALUE ('Nacional');

-- Cadastro de Classe

INSERT INTO tbClasse (CLA_NOME, CLA_PRECO) VALUE ('Lançamento', 10.00),
INSERT INTO tbClasse (CLA_NOME, CLA_PRECO) VALUE ('Catálogo', 5.00);

-- Cadastro de Titulo

INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('O Poderoso Chefão', 1972, 1, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Matrix', 1999, 4, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Jurassic Park', 1993, 13, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Titanic', 1997, 7, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Vingadores: Ultimato', 2019, 1, 1),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('O Senhor dos Anéis: O Retorno do Rei', 2003, 8, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Star Wars: Uma Nova Esperança', 1977, 4, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Harry Potter e a Pedra Filosofal', 2001, 8, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Coringa', 2019, 3, 1),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Toy Story', 1995, 9, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('O Rei Leão', 1994, 9, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Pantera Negra', 2018, 1, 1),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Interestelar', 2014, 4, 1),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Clube da Luta', 1999, 3, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Forrest Gump', 1994, 3, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Gladiador', 2000, 12, 2),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('It: A Coisa', 2017, 5, 1),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('A Origem', 2010, 4, 1),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Deadpool', 2016, 1, 1),
INSERT INTO tbTitulo (TIT_NOME, TIT_ANO, CAT_CODIGO, CLA_CODIGO) VALUE ('Cidadão Kane', 1941, 3, 2);

-- Cadastro de Filme

INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (1, 'Paramount'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (2, 'Warner Bros'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (3, 'Universal'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (4, '20th Century Fox'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (5, 'Marvel Studios'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (6, 'New Line Cinema'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (7, 'Lucasfilm'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (8, 'Warner Bros'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (9, 'DC Films'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (10, 'Pixar'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (11, 'Disney'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (12, 'Marvel Studios'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (13, 'Paramount'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (14, '20th Century Fox'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (15, 'Paramount'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (16, 'DreamWorks'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (17, 'Warner Bros'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (18, 'Warner Bros'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (19, '20th Century Fox'),
INSERT INTO tbFilme (TIT_CODIGO, FIL_NOME_DISTRIBUIDOR) VALUE (20, 'RKO Pictures');

-- Cadastro de Emprestimo e Devolução

INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (1, 3, '2024-02-01', '2024-02-08', '2024-02-07', 0.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (2, 5, '2024-01-25', '2024-02-01', '2024-02-03', 2.50),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (3, 8, '2024-01-30', '2024-02-06', '2024-02-06', 0.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (4, 2, '2024-02-05', '2024-02-12', NULL, 0.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (5, 6, '2024-02-10', '2024-02-17', NULL, 0.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (6, 9, '2024-02-15', '2024-02-22', '2024-02-25', 3.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (7, 4, '2024-02-18', '2024-02-25', NULL, 0.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (8, 7, '2024-02-20', '2024-02-27', '2024-02-27', 0.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (9, 1, '2024-02-22', '2024-02-29', NULL, 0.00),
INSERT INTO tbEmprestimoDevolucao (CLI_CODIGO, FIL_CODIGO, EMD_DATA_EMPRESTIMO, EMD_DATA_DEVOLUCAO_PREVISTA, EMD_DATA_DEVOLUCAO_EFETIVE, EMD_VALOR_MULTA) VALUE (10, 10, '2024-02-25', '2024-03-03', NULL, 0.00);